### ISSUE TITLE
Check Network connection before try to create of restore backup

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox.Windows#546]
Since we want to support Windows, Android and IOS we have to create a Interface first and then implement it for the platform we need it (currently primarily Android and Windows).

Then we need to use it in the BackupViewModel and depending on the result cancel and show an information to the user or go ahead as usual.

**Comment by MichaelAi** [comment]
As far as i know you check if there is an internet connection using this little snippet

        public static bool HasInternet()

        {
            ConnectionProfile connections = NetworkInformation.GetInternetConnectionProfile();
            bool internet = connections != null && connections.GetNetworkConnectivityLevel() == NetworkConnectivityLevel.InternetAccess;
            return internet;
        }

**Comment by NPadrutt** [comment]
ah, nice.
since this is platform specific we need to use an interface for that. I suggest we make something like "IDeviceInformation" (other name suggestions? ^^). Then we can implement it on all plattforms properly and register it in the setup.

**Comment by MichaelAi** [comment]
Ah sorry i don't know much about cross-platform development with Xamarin. IDeviceInformation sounds good.

**Comment by NPadrutt** [comment]
No worries. It ist tat complicated. You will mostly just use more Interfaces ;)
