### ISSUE TITLE
Placeholder on no account

### ISSUE THREAD

**Issue by lorenzofar** [MoneyFox/MoneyFox.Windows#594]
There should be something in the main page when there are no accounts, like in the photos app, that prompts the user to add one.

**Comment by NPadrutt** [comment]
Good idea. Do you want try to inplement that? :)

**Comment by lorenzofar** [comment]
Ok, i'll try.

**Comment by NPadrutt** [comment]
@lorenzofar how is it going? Can you manage it or do you need some help? =)

**Comment by lorenzofar** [comment]
@NPadrutt I fixed this issue with the last pull request
