### ISSUE TITLE
Inconsistent AppBar

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox.Windows#621]
From a reddit comment:
"Inconsistent apps bars: Compact at account screen, Compact but empty in statistics, non-existing at backup, minimized (and empty) at settings. Perhaps there is a better position to put the "set date range" and "new category" buttons. Additionally, since the app bar is context sensitive it may be better to put it inside the split view, though i don't think there are guidelines for that sort of thing."

**Comment by lorenzofar** [comment]
I think is better not to put an app bar in the split view but, at most, you can put it in the app shell and then manage the buttons according to the context.

**Comment by lorenzofar** [comment]
You can even use the title bar to put commands in.

**Comment by NPadrutt** [comment]
what's the advantage of just put them in the pages where you want them?

**Comment by lorenzofar** [comment]
I meant is better to put the app bar in the pages you want them to be.

**Comment by NPadrutt** [comment]
ah alright =)

**Comment by NPadrutt** [comment]
But I agree that there is potential for improvement. Especially in the settings view.

**Comment by MichaelAi** [comment]
Yeah i meant putting the appbar in the each page instead of having it over the whole view.

**Comment by NPadrutt** [comment]
In this case that would mean to just hide it or replace the buttons in it when not the category view is shown. The pivot is built in one page and different user controls, therefore we only have a single app bar AFAIK. =) that should be an easy thing.
