### ISSUE TITLE
Automatic backups

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox.Windows#641]
To make the transfer of data between the mobile apps and the desktop easier we could make an option to create backups automaticly. I see three possible ways:

1. On start check if there is an backup who's newer than the version you have on your device and if yes download it. The problem is that until you finished that you may not save something new or you have to save that temporarily.
And when you leave the app the new backup is written.

2. Check with a background task regularly if there is a new version if yes, download, if no upload.

3. Before you save a change to the database check first if there is a newer version and download first if so. Afterwards upload the new backup.

Both have the problem that it won't merge the changes if you made some on both devices. I tend to nr.1 in the moment, since it's the easiest to start, it covers a lot of cases and it gives you the option to interact with the user.
nr. 2 could be an addition to a later point to make things faster or so.

what do you mean?

**Comment by MichaelAi** [comment]
What i've done before is downloading the backup (if it's more recent than the local version of course) on start and uploading the new data every time the user made a change, with a delay to give the user time to make more changes. Every subsequent change within that delay window will add to the countdown until the sync. Force the sync when the app is suspended or terminated. The data will be stored locally before the sync so as not to lose them in case of a crash.

**Comment by NPadrutt** [comment]
That sounds like a good plan. Have you done it on onedrive aswell?

**Comment by MichaelAi** [comment]
Yes.

**Comment by NPadrutt** [comment]
do you wanna give this a try?

**Comment by MichaelAi** [comment]
I could, but i'll need you to create the classes you want me write the code into. And hook it up so that it triggers every time the user makes a change. I'm not sure how you handled that part.

**Comment by NPadrutt** [comment]
I don't have a concrete idea where in what classes to put it. So feel free to put it where you think it's best. If t here are any issue with that we will see it on your pull request =)

Regarding the hooking up.. We could place that into the repositories. They are responsible to do the saving etc. Otherwise we coudl also do it in the VM's.. but I guess the repositories are the better place for that.

**Comment by MichaelAi** [comment]
Yeah the repositories seem the best place to do it. I'll have a more thorough look when i have time.

**Comment by NPadrutt** [comment]
nice :)

**Comment by MichaelAi** [comment]
I suppose the backing up is done in MoneyManager / Src / MoneyManager.Core / OneDriveService.cs , right?

**Comment by NPadrutt** [comment]
Yeah, exactly :)
