### ISSUE TITLE
Colors in light mode

### ISSUE THREAD

**Issue by lorenzofar** [MoneyFox/MoneyFox.Windows#850]
When the app runs with light theme, some texts cannot be seen, because they are of the same color of the background. Furthermore, the black of the alternate list view in the accounts page clashes with the white background of the page.
![screenshot 166](https://cloud.githubusercontent.com/assets/9354606/14711564/066daf2c-07da-11e6-9a62-b4ff1862fd64.png)
![screenshot 164](https://cloud.githubusercontent.com/assets/9354606/14711565/0677bd82-07da-11e6-8e39-755d866204a2.png)

**Comment by NPadrutt** [comment]
good point!

**Comment by NPadrutt** [comment]
This was fixed in the last PR. Thanks for the help @MichaelAi
