### ISSUE TITLE
Wrong page header when adding a payment

### ISSUE THREAD

**Issue by lorenzofar** [MoneyFox/MoneyFox.Windows#865]
I think the page header of the ModifyPaymentView.xaml is wrong (see attached screenshot)
![screenshot 186](https://cloud.githubusercontent.com/assets/9354606/14854783/5c37b838-0c91-11e6-9eac-a9bbcda29d73.png)

**Comment by NPadrutt** [comment]
Indeed.  IMHO cool would be if the title would reflect the type of the transaction.
Wanna have a look at that?

**Comment by lorenzofar** [comment]
Yep, I'll have a look at that.

**Comment by NPadrutt** [comment]
thanks =)

**Comment by lorenzofar** [comment]
I added this in #866
