### ISSUE TITLE
Not all texts are translated to german

### ISSUE THREAD

**Issue by dignityinside** [MoneyFox/MoneyFox.Windows#900]
Please translate all texts to German for example Categories in menu must be Kategorien. In menu Statistics not all texts are German ;)

**Comment by NPadrutt** [comment]
Yep, true.
We are preparing a rather big update. I guess the translation you mention are fixed there. Next will come with another update (guess today). Feel free to to test it out and give feedback!
You can find the link in the readme (or [here](https://github.com/MoneyFox/MoneyFox.Windows#try-it))

**Comment by NPadrutt** [comment]
I will close this issue. as far as I'm aware of german is translated. not to mention that most of the other have missing translations since I can't do the translations myself.
